import os
import time
from PySide6.QtWidgets import QDialog, QVBoxLayout, QPushButton, QHBoxLayout, QMessageBox, QLabel
from PySide6.QtCore import QUrl, Signal, Qt
from PySide6.QtNetwork import QNetworkCookie

from app_config import app_data_dir


class AuthBrowserDialog(QDialog):
    cookies_extracted = Signal(str)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Log in to YouTube")
        self.resize(900, 700)
        self.setWindowFlags(self.windowFlags() | Qt.WindowMaximizeButtonHint | Qt.WindowMinimizeButtonHint)
        
        try:
            from PySide6.QtWebEngineWidgets import QWebEngineView
            from PySide6.QtWebEngineCore import QWebEngineProfile, QWebEnginePage
        except ImportError:
            QMessageBox.critical(self, "Error", "WebEngine is not installed. Please install PySide6-WebEngine.")
            self.reject()
            return
            
        self.layout = QVBoxLayout(self)
        
        info_label = QLabel("Please log in to YouTube. Once logged in, click the 'Done' button below to save your cookies.")
        info_label.setObjectName("MutedText")
        info_label.setWordWrap(True)
        self.layout.addWidget(info_label)
        
        self.browser = QWebEngineView(self)
        
        # We use an off-the-record profile so cookies are clean and don't conflict,
        # but persistent is also fine. Let's use a named off-the-record or persistent profile.
        self.profile = QWebEngineProfile("yt_auth_profile", self)
        
        # Set User-Agent to avoid Google's "Browser not secure" warnings.
        user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
        self.profile.setHttpUserAgent(user_agent)
        
        # We track cookies
        self.store = self.profile.cookieStore()
        self.cookies = {}
        self.store.cookieAdded.connect(self._on_cookie_added)
        
        self.page = QWebEnginePage(self.profile, self.browser)
        self.browser.setPage(self.page)
        
        # Load YouTube login
        login_url = QUrl("https://accounts.google.com/ServiceLogin?service=youtube&continue=https://www.youtube.com/")
        self.browser.load(login_url)
        self.layout.addWidget(self.browser, 1)
        
        btn_layout = QHBoxLayout()
        self.cancel_btn = QPushButton("Cancel")
        self.cancel_btn.clicked.connect(self.reject)
        
        self.done_btn = QPushButton("Done (Save Cookies && Close)")
        self.done_btn.clicked.connect(self._save_cookies)
        self.done_btn.setDefault(True)
        
        btn_layout.addWidget(self.cancel_btn)
        btn_layout.addStretch()
        btn_layout.addWidget(self.done_btn)
        
        self.layout.addLayout(btn_layout)

    def _on_cookie_added(self, cookie: QNetworkCookie):
        domain = cookie.domain()
        name = cookie.name().data().decode('utf-8', 'replace')
        self.cookies[(domain, name)] = cookie

    def _save_cookies(self):
        out_path = os.path.join(app_data_dir(), "embedded_cookies.txt")
        try:
            with open(out_path, "w", encoding="utf-8") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by YTDownloader Embedded Browser\n\n")
                for (domain, name), cookie in self.cookies.items():
                    if not domain.endswith("youtube.com") and not domain.endswith("google.com"):
                        continue
                        
                    domain_str = domain
                    include_subdomains = "TRUE" if domain_str.startswith(".") else "FALSE"
                    path_str = cookie.path()
                    secure = "TRUE" if cookie.isSecure() else "FALSE"
                    
                    expiration = 0
                    if not cookie.isSessionCookie():
                        expiration = cookie.expirationDate().toSecsSinceEpoch()
                    
                    value = cookie.value().data().decode('utf-8', 'replace')
                    
                    f.write(f"{domain_str}\t{include_subdomains}\t{path_str}\t{secure}\t{expiration}\t{name}\t{value}\n")
            
            self.cookies_extracted.emit(out_path)
            self.accept()
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Failed to save cookies: {e}")
